#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=busco
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=10gb
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=10
#SBATCH --nodes=1
#SBATCH --output=busco_%j.out
#SBATCH --error=busco_%j.err

module load busco/4.1.4
export BUSCO_CONFIG_FILE="/blue/soltis/kasey.pham/tprat_genome/annotation/augustus/config.ini"
export AUGUSTUS_CONFIG_PATH="/blue/soltis/kasey.pham/tprat_genome/busco/augustus_config"

busco
