#!/bin/bash
#SBATCH --job-name=maker01
#SBATCH --output=maker01_%j.out
#SBATCH --error=maker01_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --qos=soltis-b
#SBATCH --account=soltis
#SBATCH --nodes=6                       # Number of nodes
#SBATCH --ntasks=12                     # Number of MPI ranks
#SBATCH --cpus-per-task=1               # Number of cores per MPI rank
#SBATCH --ntasks-per-node=2             # How many tasks on each node
#SBATCH --ntasks-per-socket=1           # How many tasks on each CPU or socket
#SBATCH --distribution=cyclic:cyclic    # Distribute tasks cyclically on nodes and sockets
#SBATCH --mem-per-cpu=4gb               # Memory per processor
#SBATCH -t 4-00:00:00

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load intel/2020.0.166
module load openmpi/4.0.5
module load maker/3.01.03

srun --mpi=pmix maker -base maker01 maker01_opts.ctl maker01_bopts.ctl maker01_exe.ctl
