#!/bin/bash
#SBATCH --job-name=maker02
#SBATCH --output=maker02_%j.out
#SBATCH --error=maker02_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --qos=soltis
#SBATCH --account=soltis
#SBATCH --nodes=6                       # Number of nodes
#SBATCH --ntasks=12                     # Number of MPI ranks
#SBATCH --cpus-per-task=1               # Number of cores per MPI rank
#SBATCH --ntasks-per-node=2             # How many tasks on each node
#SBATCH --ntasks-per-socket=1           # How many tasks on each CPU or socket
#SBATCH --distribution=cyclic:cyclic    # Distribute tasks cyclically on nodes and sockets
#SBATCH --mem-per-cpu=1gb               # Memory per processor
#SBATCH -t 14-00:00:00

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load intel/2020.0.166
module load openmpi/4.0.5
module load maker/3.01.03
module load snap/20100728

export AUGUSTUS_CONFIG_PATH=/blue/soltis/kasey.pham/tprat_genome/busco/augustus_config

srun --mpi=pmix maker -base maker02 maker02_opts.ctl maker02_bopts.ctl maker02_exe.ctl
