#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=procmak2
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=10gb
#SBATCH --time=96:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=process_maker02_%j.out
#SBATCH --error=process_maker02_%j.err

module purge
module load maker

maker2zff -x 0.25 -l 50 -d /blue/soltis/kasey.pham/tprat_genome/annotation/maker01/maker01.maker.output/maker01_master_datastore_index.log
