#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=procreps
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=30gb
#SBATCH --time=10:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=procreps_%j.out
#SBATCH --error=procreps_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load repeatmasker/4.0.9

ProcessRepeats -species asteraceae tprat_repeat_fullmask.cat
