#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=repbase
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=100gb
#SBATCH --time=96:00:00
#SBATCH --cpus-per-task=12
#SBATCH --nodes=1
#SBATCH --output=repbase_%j.out
#SBATCH --error=repbase_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load repeatmasker/4.0.9
ASSEMB_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/refs/Eglobulus_genome_X46"

RepeatMasker -pa 12 -e ncbi -species eucalyptus -dir eucalyptus "$ASSEMB_DIR"/EGLOB-X46.v1.0.fa
