#Input section 
input:
  #input fasta file name
  fasta: Eglob_fdiffs_AUSX01_homol_prot.fas
  # output file basename
  basename: fdiffs
  #input NCBI taxonomy id
  taxon: "71139 "
  # Name of the species
  species: "Eucalyptus grandis"
  # Email is mandatory
  email: kasey.pham@ufl.edu
  #Number of CPUs used for tools
  cpus: 8
  #Whether openmpi should be used
  mpi: False
  #what the name of the temporary directory is
  tmpdir: "/tmpdir"
