#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=hepop
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=600mb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=he_pops_%j.out
#SBATCH --error=he_pops_%j.err

module load conda 

ENV_DIR="/blue/soltis/kasey.pham/conda/envs"
SCRIPT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"
VCF_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/04.filter_snps/maf0.00"
CHRLIST_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/genome_scan"
STRUCT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/pop_stats/struct_files"

conda activate "$ENV_DIR"/euc_hyb_reseq

# E. cordata
python "$SCRIPT_DIR"/stats_windows.py "$VCF_DIR"/meehan_all_fil_maf0.00_snps.vcf He 5000 2500 "$STRUCT_DIR"/cord_structure.json "$STRUCT_DIR"/cord_outgroup.json "$CHRLIST_DIR"/chr_list.txt cordata_he_distr.tab

# Meehan Range E. globulus
python "$SCRIPT_DIR"/stats_windows.py "$VCF_DIR"/meehan_all_fil_maf0.00_snps.vcf He 5000 2500 "$STRUCT_DIR"/glob_mr_structure.json "$STRUCT_DIR"/glob_mr_outgroup.json "$CHRLIST_DIR"/chr_list.txt globmr_he_distr.tab

# Reference E. globulus
python "$SCRIPT_DIR"/stats_windows.py "$VCF_DIR"/meehan_all_fil_maf0.00_snps.vcf He 5000 2500 "$STRUCT_DIR"/glob_ref_structure.json "$STRUCT_DIR"/glob_ref_outgroup.json "$CHRLIST_DIR"/chr_list.txt globref_he_distr.tab

# E. globulus
python "$SCRIPT_DIR"/stats_windows.py "$VCF_DIR"/meehan_all_fil_maf0.00_snps.vcf He 5000 2500 "$CHRLIST_DIR"/glob_structure.json "$CHRLIST_DIR"/glob_outgroup.json "$CHRLIST_DIR"/chr_list.txt glob_he_distr.tab