#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=chr01_w_avgrs
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=40gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=glob_chr01_whole_avg_rsq_%j.out
#SBATCH --error=glob_chr01_whole_avg_rsq_%j.err

module purge
module load python/3.8
SCRIPT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"
TAB_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/ld/glob/emerald/genome_wide"

python "$SCRIPT_DIR"/average_r2.py "$TAB_DIR"/glob_Chr01_ld.txt.gz glob_Chr01_ld_avg.csv
