#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=glob_ldhat_in
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=300mb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=glob_get_ldhat_in_%j.out
#SBATCH --error=glob_get_ldhat_in_%j.err

module purge
module load python/3.8
SCRIPT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"
VCF_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/ld/glob/recomb"
# declare -a NAMELIST=(Chr01 Chr02 Chr03 Chr04 Chr05 Chr06 Chr07 Chr08 Chr09 Chr10 Chr11)
# declare -a SIZELIST=(42219.553 50828.380 65547.241 38599.333 62919.971 52140.660 54252.628 70214.608 38300.324 38722.660 42056.460 47499.628)

# for i in $(seq 0 10)
# do
#     python "$SCRIPT_DIR"/get_ldhat_in.py "$VCF_DIR"/globMR_fil_biallelic.vcf.gz glob_ldhat "${NAMELIST[i]}" "${SIZELIST[i]}"
# done

declare -a NAMELIST=(Chr01 Chr02 Chr03 Chr04 Chr05 Chr06 Chr07 Chr08 Chr09 Chr10 Chr11)
declare -a SIZELIST=(42219553 50828380 65547241 38599333 62919971 52140660 54252628 70214608 38300324 38722660 42056460 47499628)

for i in $(seq 0 10)
do
    echo doing "${NAMELIST[i]}"
    QUOTIENT=$(("${SIZELIST[i]}"/5))
    for j in $(seq 0 4)
    do
        START_IND=$(("$j" * "$QUOTIENT"))
        if (("$j" < 4 )); then
            END_IND=$(((("$j" + 1) * "$QUOTIENT") - 1))
        else
            END_IND="${SIZELIST[i]}"
        fi 
        echo doing region "$START_IND" to "$END_IND"
        python "$SCRIPT_DIR"/get_ldhat_in.py "$VCF_DIR"/globMR_fil_biallelic.vcf.gz glob_ldhat "${NAMELIST[i]}" "$START_IND" "$END_IND"
    done
done