#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=glob_lkup
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=2gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=glob_lookup_%j.out
#SBATCH --error=glob_lookup_%j.err

module purge
module load ldhat/2.2a
declare -a NAMELIST=(Chr01 Chr02 Chr03 Chr04 Chr05 Chr06 Chr07 Chr08 Chr09 Chr10 Chr11)

for NAME in "${NAMELIST[@]}"
do
    "$HPC_LDHAT_BIN"/pairwise -seq glob_ldhat_"$NAME".sites -loc glob_ldhat_"$NAME".locs -lk glob_lookup.txt -prefix glob_ldhat_"$NAME"
done