#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=glob_lkup
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=2gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=glob_lookup_%j.out
#SBATCH --error=glob_lookup_%j.err

module purge
module load ldhat/2.2a

"$HPC_LDHAT_BIN"/complete -n 40 -rhomax 100 -n_pts 101 -theta 0.00768