#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=plink00g
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=30gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=12
#SBATCH --nodes=1
#SBATCH --output=plink_%j.out
#SBATCH --error=plink_%j.err

module load plink/1.90b3.39 

IN_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/ld/vcf_files"
LIST_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/ld/glob"
declare -a CHROMOSOMES=(Chr01 Chr02 Chr03 Chr04 Chr05 Chr06 Chr07 Chr08 Chr09 Chr10 Chr11)

for CHR in "${CHROMOSOMES[@]}"
do
    plink --vcf "$IN_DIR"/"$CHR"_snps_fil.vcf --keep "$LIST_DIR"/Eglobulus.fam --double-id --allow-extra-chr --set-missing-var-ids @:# --maf 0.00000001 --mind 0.5 --r2 gz --ld-window 100001 --ld-window-kb 1000 -ld-window-r2 0 --make-bed  --vcf-half-call m --thin 0.5 --out "$CHR"_glob00 --threads 12
done
