#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=beagle
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=50gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=12
#SBATCH --nodes=1
#SBATCH --output=beagle_%j.out
#SBATCH --error=beagle_%j.err

module load beagle/5.2

WDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/05.analyses/admix_map"
NAME="all_to_ASM1654582_fil_maf0.05_nomiss_manedit"

"$HPC_BEAGLE_BIN"/beagle gt="$NAME".vcf out="$NAME"_phased impute=false burnin=5 iterations=20 phase-states=280 nthreads=11
