#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=flare
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=10gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=12
#SBATCH --nodes=1
#SBATCH --output=flare_test_%j.out
#SBATCH --error=flare_test_%j.err

module load java/11.0.1

FLARE_DIR="/blue/soltis/kasey.pham/bin/flare"
WDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/admix_map"
NAME="test_snps_nohap_phased"

java -Xmx10g -jar "$FLARE_DIR"/flare.jar ref="$WDIR"/"$NAME".vcf.gz ref-panel=ref_panel.txt gt="$WDIR"/"$NAME".vcf.gz gt-samples=gt_samples.txt map=1060_LH_F2_manual_copy.map nthreads=12 out=test_admap