#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=refvcf
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=12
#SBATCH --nodes=1
#SBATCH --output=get_ref_vcf_%j.out
#SBATCH --error=get_ref_vcf_%j.err

module purge
module load bcftools/1.15
VCFDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/04.filter_snps/filtered_var"

ls "$VCFDIR"/*.vcf.gz > files_to_concat.txt
bcftools concat --file-list files_to_concat.txt --output-type z --threads 12 | bcftools view --samples-file ref_samples.txt --min-af 0.05 --output-type v --threads 12 --output "$VCFDIR"/refs_fil_maf05.vcf