#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=pcadapt
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=pcadapt_%j.out
#SBATCH --error=pcadapt_%j.err

module purge
module load R/4.2
WDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/pca_corr"
SCRIPTS_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"

Rscript get_corr_snps.r "$WDIR"/