#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=merge_chr03
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=30gb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=merge_chr03_%j.out
#SBATCH --error=merge_chr03_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module load picard/2.25.5
VCF_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/03.freebayes/parallel/Chr03"
OUT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/03.freebayes"

picard MergeVcfs -I "$VCF_DIR"/vcfs_list.txt -O "$OUT_DIR"/chr03.vcf


