#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=all_call_stats
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=500mb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=all_call_stats_%j.out
#SBATCH --error=all_call_stats_%j.err

module load vcftools/0.1.16 
BEDDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/ancestry_hmm/char_regions"
VCFDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/04.filter_snps"

# Chromosome 6
vcftools --gzvcf "$VCFDIR"/all_fil.vcf.gz --out all_ahmm_chr06 --remove-indv SRR10339635 --bed "$BEDDIR"/chr06_shared.bed --site-mean-depth
vcftools --gzvcf "$VCFDIR"/all_fil.vcf.gz --out all_ahmm_chr06 --remove-indv SRR10339635 --bed "$BEDDIR"/chr06_shared.bed --site-quality
vcftools --gzvcf "$VCFDIR"/all_fil.vcf.gz --out all_ahmm_chr06 --remove-indv SRR10339635 --bed "$BEDDIR"/chr06_shared.bed --missing-site
vcftools --gzvcf "$VCFDIR"/all_fil.vcf.gz --out all_ahmm_chr06 --remove-indv SRR10339635 --bed "$BEDDIR"/chr06_shared.bed --get-INFO GL

# Chromosome 7
vcftools --gzvcf "$VCFDIR"/all_fil.vcf.gz --out all_ahmm_chr07 --remove-indv SRR10339635 --bed "$BEDDIR"/chr07_shared.bed --site-mean-depth
vcftools --gzvcf "$VCFDIR"/all_fil.vcf.gz --out all_ahmm_chr07 --remove-indv SRR10339635 --bed "$BEDDIR"/chr07_shared.bed --site-quality
vcftools --gzvcf "$VCFDIR"/all_fil.vcf.gz --out all_ahmm_chr07 --remove-indv SRR10339635 --bed "$BEDDIR"/chr07_shared.bed --missing-site
vcftools --gzvcf "$VCFDIR"/all_fil.vcf.gz --out all_ahmm_chr07 --remove-indv SRR10339635 --bed "$BEDDIR"/chr07_shared.bed --get-INFO GL

# Chromosome 8
vcftools --gzvcf "$VCFDIR"/all_fil.vcf.gz --out all_ahmm_chr08 --remove-indv SRR10339635 --bed "$BEDDIR"/chr08_shared.bed --site-mean-depth
vcftools --gzvcf "$VCFDIR"/all_fil.vcf.gz --out all_ahmm_chr08 --remove-indv SRR10339635 --bed "$BEDDIR"/chr08_shared.bed --site-quality
vcftools --gzvcf "$VCFDIR"/all_fil.vcf.gz --out all_ahmm_chr08 --remove-indv SRR10339635 --bed "$BEDDIR"/chr08_shared.bed --missing-site
vcftools --gzvcf "$VCFDIR"/all_fil.vcf.gz --out all_ahmm_chr08 --remove-indv SRR10339635 --bed "$BEDDIR"/chr08_shared.bed --get-INFO GL
