#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=ahmm_regions
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=ahmm_regions_%j.out
#SBATCH --error=ahmm_regions_%j.err

module load R/4.2
LIST_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/ancestry_hmm"
POST_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/ancestry_hmm/posteriors"
SCRIPT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"

while read NAME
do
    echo doing "$NAME"
    Rscript "$SCRIPT_DIR"/get_intr_bed.r "$POST_DIR"/"$NAME".posterior 0.95 0.90 750 0.85 ind_region_beds/"$NAME"_ahmm_regions.bed
done < "$LIST_DIR"/Eglobulus_MR.txt
