#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=makebimbam
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=2gb
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=make_bimbam_%j.out
#SBATCH --error=make_bimbam_%j.err

module purge
module load plink/1.90b3.39 

VCF="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/04.filter_snps/all_fil.vcf.gz"
WDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/elai"

# MR cordata
plink --vcf "$VCF" --double-id --allow-extra-chr 0 --set-missing-var-ids @:# --keep "$WDIR"/Ecordata.fam --out "$WDIR"/cord --recode bimbam

# ref globulus
plink --vcf "$VCF" --double-id --allow-extra-chr 0 --set-missing-var-ids @:# --keep "$WDIR"/Eglobulus_ref.fam --out "$WDIR"/glob_pure --recode bimbam

# MR globulus
plink --vcf "$VCF" --double-id --allow-extra-chr 0 --set-missing-var-ids @:# --keep "$WDIR"/Eglobulus_MR.fam --out "$WDIR"/glob_mr --recode bimbam