#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis
#SBATCH --job-name=fbchr1
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=7gb
#SBATCH --time=16-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=freebayes_NC052612_%j.out
#SBATCH --error=freebayes_NC052612_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load freebayes/1.3.2

freebayes -L /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/freebayes/bam_inputs.txt -f /blue/soltis/kasey.pham/euc_hyb_reseq/refs/ASM1654582v1/GCF_016545825.1_ASM1654582v1_genomic.fna -r NC_052612.1 -v /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/freebayes/max_dp_3000/NC_052612.vcf -g 3000
