#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=mergevcfs
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=20gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=12
#SBATCH --nodes=1
#SBATCH --output=merge_filtered_%j.out
#SBATCH --error=merge_filtered_%j.err

module purge
module load bcftools/1.15

VAR_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/04.filter_snps/filtered_var"
INVAR_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/04.filter_snps/filtered_invar"
declare -a VCFLIST=(chr01 chr02 chr03 chr04 chr05 chr06 chr07 chr08 chr09 chr10 chr11 chrUn)

for NAME in "${VCFLIST[@]}"
do
    tabix "$VAR_DIR"/"$NAME"_snps_fil.vcf.gz
    tabix "$INVAR_DIR"/"$NAME"_invar_fil.vcf.gz
    bcftools concat --allow-overlaps -O z --threads 12 "$VAR_DIR"/"$NAME"_snps_fil.vcf.gz "$INVAR_DIR"/"$NAME"_invar_fil.vcf.gz | bcftools sort -m 19500 -O z - > "$NAME"_fil.vcf.gz
done
