#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=mergechr
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=5gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=12
#SBATCH --nodes=1
#SBATCH --output=merge_fil_chr_%j.out
#SBATCH --error=merge_fil_chr_%j.err

module purge
module load bcftools/1.15

WDIR="/orange/soltis/kasey.pham/eucalyptus_hyb_reseq/06.snp_filtering/"
declare -a VCFLIST=(chr01 chr02 chr03 chr04 chr05 chr06 chr07 chr08 chr09 chr10 chr11 chrUn)

for NAME in "${VCFLIST[@]}"
do
    tabix "$WDIR"/"$NAME"_fil.vcf.gz
done

ls "$WDIR"/*_fil.vcf.gz > "$WDIR"/vcf_list.txt
bcftools concat -O z --threads 12 -f "$WDIR"/vcf_list.txt -o "$WDIR"/all_fil.vcf.gz