#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=plot_snp_stats
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=30gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=plot_snp_stats_%j.out
#SBATCH --error=plot_snp_stats_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load R/4.2

declare -a VCFLIST=(chr01 chr02 chr03 chr04 chr05 chr06 chr07 chr08 chr09 chr10 chr11 chrUn)
SCRIPT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"

for NAME in "${VCFLIST[@]}"
do
    Rscript "$SCRIPT_DIR"/plot_snp_stats.r "$NAME"_variant_dp.tab "$NAME"_variant_gq.tab "$NAME"_variant_sp.tab "$NAME"_variant_info.tab "$NAME"
done