#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=splitbam
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=5gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=split_bam_%j.out
#SBATCH --error=split_bam_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load samtools/1.15

LIST_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq"
IN_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup"
CHR03_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/03.freebayes/parallel/Chr03"
CHR05_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/03.freebayes/parallel/Chr05"

# Chromosome 3
while read NAME
do
    while read SECTION
    do
        samtools view -b -h -o "$CHR03_DIR"/bamfiles/"$NAME"_Chr03_"$SECTION".bam "$IN_DIR"/"$NAME"_marked.bam Chr03:"$SECTION"
    done < "$CHR03_DIR"/chr03_section_list.txt
done < "$LIST_DIR"/seq_ids.txt

while read SECTION
    do
        samtools view -b -h -o "$CHR03_DIR"/bamfiles/SRR10339635_Chr03_"$SECTION".bam "$IN_DIR"/SRR10339635_marked.bam Chr03:"$SECTION"
    done < "$CHR03_DIR"/chr03_section_list.txt

# Chromosome 5
while read NAME
do
    while read SECTION
    do
        samtools view -b -h -o "$CHR05_DIR"/bamfiles/"$NAME"_Chr05_"$SECTION".bam "$IN_DIR"/"$NAME"_marked.bam Chr05:"$SECTION"
    done < "$CHR05_DIR"/chr05_section_list.txt
done < "$LIST_DIR"/seq_ids.txt

while read SECTION
do
    samtools view -b -h -o "$CHR05_DIR"/bamfiles/SRR10339635_Chr05_"$SECTION".bam "$IN_DIR"/SRR10339635_marked.bam Chr05:"$SECTION"
done < "$CHR05_DIR"/chr05_section_list.txt