#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=splitindels0
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=splitindels_%j.out
#SBATCH --error=splitindels_%j.err

module load bcftools/1.15
module load vcftools/0.1.16
NAME="meehan_all_fil_maf0.00"

bcftools annotate -x FORMAT/PL,FORMAT/AD,FORMAT/AO,FORMAT/QA -O v -o - "$NAME".vcf | vcftools --vcf - --remove-indels --recode --stdout > "$NAME"_snps.vcf

bcftools annotate -x FORMAT/PL,FORMAT/AD,FORMAT/AO,FORMAT/QA -O v -o - "$NAME".vcf | vcftools --vcf - --keep-only-indels --recode --stdout > "$NAME"_indels.vcf
