#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=vcfdupes0
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=10gb
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=vcf_dupes_%j.out
#SBATCH --error=vcf_dupes_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load python/3.8
SCRIPT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"
INFILE="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/04.filter_snps/maf0.00/meehan_all_fil_maf0.00_snps.vcf"

python "$SCRIPT_DIR"/check_vcf_duplicates.py "$INFILE" "meehan_all_fil_maf0.00_snps_first.txt" "meehan_all_fil_maf0.00_snps_dupes.txt" "meehan_all_fil_maf0.00_snps_nodupes.vcf"
