#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=avgr2_05c
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=80gb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=avg_r2_%j.out
#SBATCH --error=avg_r2_%j.err

module load python/3.8 

SCRIPTS_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"
WDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/ld/cord/maf0.05"
declare -a CHROMOSOMES=(Chr01 Chr02 Chr03 Chr04 Chr05 Chr06 Chr07 Chr08 Chr09 Chr10 Chr11)

for NAME in "${CHROMOSOMES[@]}"
do
	python "$SCRIPTS_DIR"/average_r2.py  "$WDIR"/"$NAME"_cord05.ld.gz "$WDIR"/"$NAME"_r2_cord05.csv
done
