#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=cordm1_avgrs
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=15gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=cord_whole_mac01_avg_rsq_%j.out
#SBATCH --error=cord_whole_mac01_avg_rsq_%j.err

module purge
module load python/3.8
SCRIPT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"
TAB_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/ld/cord/emerald/genome_wide"
declare -a NAMELIST=(Chr01 Chr02 Chr03 Chr04 Chr05 Chr06 Chr07 Chr08 Chr09 Chr10 Chr11)

for NAME in "${NAMELIST[@]}"
do
    python "$SCRIPT_DIR"/average_r2.py -i "$TAB_DIR"/cord_"$NAME"_ld.txt.gz -o cord_"$NAME"_ld_avg.csv
done