#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=cw_mac1_cfit
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=cord_genwide_mac01_curvefit_%j.out
#SBATCH --error=cord_genwide_mac01_curvefit_%j.err

module purge
module load R/4.2
SCRIPT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"

Rscript "$SCRIPT_DIR"/fit_rsq_curve.r -f chr_r2_tab_list.txt -o genwide_ld_mac01.txt -m 100 -r 0.2 -g TRUE
