#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=gomap04
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=10gb
#SBATCH --time=48:00:00
#SBATCH --cpus-per-task=9
#SBATCH --nodes=1
#SBATCH --output=gomap04_%j.out
#SBATCH --error=gomap04_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module load gomap/1.3

export GOMAP_LOC="/apps/gomap/1.3/GOMAP-singularity"

$GOMAP_LOC/run-GOMAP-SINGLE.sh --step=mixmeth-blast --config=config.yml
