#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=splitindelstest
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=splitindels_test_%j.out
#SBATCH --error=splitindels_test_%j.err

module load vcftools/0.1.16
NAME="chr01_fil"

cat "$NAME".vcf | vcftools --vcf - --remove-indels --recode --stdout > test_snps.vcf
