#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=splitbam78
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=5gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=split_bam_78_%j.out
#SBATCH --error=split_bam_78_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load samtools/1.15

LIST_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq"
IN_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup"
CHR03_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/03.freebayes/parallel/split_bam_files/Chr07"
CHR05_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/03.freebayes/parallel/split_bam_files/Chr08"

# Chromosome 7
while read NAME
do
    while read SECTION
    do
        samtools view -b -h -o "$NAME"_Chr07_"$SECTION".bam "$IN_DIR"/"$NAME"_marked.bam Chr07:"$SECTION"
    done < "$CHR07_DIR"/chr07_section_list.txt
done < "$LIST_DIR"/seq_ids.txt

# Chromosome 5
while read NAME
do
    while read SECTION
    do
        samtools view -b -h -o "$NAME"_Chr08_"$SECTION".bam "$IN_DIR"/"$NAME"_marked.bam Chr08:"$SECTION"
    done < "$CHR08_DIR"/chr08_section_list.txt
done < "$LIST_DIR"/seq_ids.txt
