#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=gtcounts
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=gt_counts_%j.out
#SBATCH --error=gt_counts_%j.err

module load vcftools/0.1.16 

INFILE="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/04.filter_snps/maf0.00/meehan_all_fil_maf0.00_snps.vcf"
POPLIST_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/genome_scan"

# Get genotype counts for E. cordata
vcftools --vcf "$INFILE" --out cord_counts --keep "$POPLIST_DIR"/Ecordata.txt --min-alleles 1 --max-alleles 2 --counts

# E. globulus ref
vcftools --vcf "$INFILE" --out glob_counts --keep "$POPLIST_DIR"/Eglobulus_ref.txt --min-alleles 1 --max-alleles 2 --counts

# Introgressants
while read NAME
do
    vcftools --vcf "$INFILE" --out "$NAME"_counts --indv "$NAME" --min-alleles 1 --max-alleles 2 --counts
done < "$POPLIST_DIR"/Eglobulus_MR.txt