#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=hmm_lai
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=hmm_ancestry_%j.out
#SBATCH --error=hmm_ancestry_%j.err

module load armadillo

# Run Ancestry_HMM
# Arguments:
# -i: input of genotype counts among reference and introgressed samples
# -s: ploidy of each sample, all diploid
# -a: two source populations, 0 (E. globulus) contributed 98% of variation and 1 (E. cordata) contributed 2%
# -p: first ancestry pulse for glob background, num generations set above limit to indicate starting background, 98% of current admixed genomes 
# -p: second ancestry pulse for cordy background, start at 1700 generations (assuming pleistocene admixture and generation times of 10 years) and optimize, 2% of current admixed genomes but optimize estimate
# -g: genotype counts provided rather than read pileups
# -b: do 100 bootstraps of 10,000 SNP blocks
# -ne: effective population size of... ???

ancestry_hmm –i [input_file] –s sample_ploidy.txt -a 2 0.98 0.02 -p 0 100000 0.98 -p 1 -1700 -0.02 -g -b 100 10000 # -ne ???
