#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=liftoff
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=2gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=10
#SBATCH --nodes=1
#SBATCH --output=liftoff_%j.out
#SBATCH --error=liftoff_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module load liftoff/1.4.2
TARGET_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/refs/Eglobulus_genome_X46"
ASSEMB_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/refs/AUSX01_v2/assembly"
ANNOT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/refs/AUSX01_v2/annotation"

liftoff -g "$ANNOT_DIR"/Egrandis_297_v2.0.gene.gff3 -o Eglob_X46_liftoff_20230731.gff3 -u Eglob_X46_liftoff_20230731_unmapped.txt -exclude_partial -a 0.7 -s 0.7 -flank 0.1 -chroms chr_X46_to_AUSX01.txt -unplaced Eglob_X46_liftoff_20230731_unplaced.txt -copies -sc 0.975 -p 9 -polish "$TARGET_DIR"/EGLOB-X46.v1.0.fa "$ASSEMB_DIR"/Egrandis_297_v2.0.fa
