#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=outl_stats
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=stats_outlier_check_%j.out
#SBATCH --error=stats_outlier_check_%j.err

module load conda 
conda activate "$ENV_DIR"/euc_hyb_reseq

python stat_outlier_check.py

