#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=pipop
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=600mb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=pi_pops_%j.out
#SBATCH --error=pi_pops_%j.err

module load conda 

ENV_DIR="/blue/soltis/kasey.pham/conda/envs"
SCRIPT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"
VCF_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/04.filter_snps/maf0.00"
CHRLIST_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/genome_scan"
STRUCT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/pop_stats/struct_files"

conda activate "$ENV_DIR"/euc_hyb_reseq

# E. cordata
python "$SCRIPT_DIR"/stats_windows.py "$VCF_DIR"/meehan_all_fil_maf0.00_snps.vcf Pi 5000 2500 "$STRUCT_DIR"/cord_structure.json "$STRUCT_DIR"/cord_outgroup.json "$CHRLIST_DIR"/chr_list.txt cordata_pi_distr.tab

# Meehan Range E. globulus
python "$SCRIPT_DIR"/stats_windows.py "$VCF_DIR"/meehan_all_fil_maf0.00_snps.vcf Pi 5000 2500 "$STRUCT_DIR"/glob_mr_structure.json "$STRUCT_DIR"/glob_mr_outgroup.json "$CHRLIST_DIR"/chr_list.txt globmr_pi_distr.tab

# Reference E. globulus
python "$SCRIPT_DIR"/stats_windows.py "$VCF_DIR"/meehan_all_fil_maf0.00_snps.vcf Pi 5000 2500 "$STRUCT_DIR"/glob_ref_structure.json "$STRUCT_DIR"/glob_ref_outgroup.json "$CHRLIST_DIR"/chr_list.txt globref_pi_distr.tab

# Between references
python "$SCRIPT_DIR"/stats_windows.py "$VCF_DIR"/meehan_all_fil_maf0.00_snps.vcf Pi 5000 2500 "$STRUCT_DIR"/ref_structure.json "$STRUCT_DIR"/ref_outgroup.json "$CHRLIST_DIR"/chr_list.txt ref_pi_distr.tab

# Between all
python "$SCRIPT_DIR"/stats_windows.py "$VCF_DIR"/meehan_all_fil_maf0.00_snps.vcf Pi 5000 2500 "$STRUCT_DIR"/all_structure.json "$STRUCT_DIR"/all_outgroup.json "$CHRLIST_DIR"/chr_list.txt all_pi_distr.tab