#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=summstats
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=600mb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=summarize_stats_%j.out
#SBATCH --error=summarize_stats_%j.err

module load R/4.2

SCRIPT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"
WDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/pop_stats"

# Dxy - E. globulus ref to E. cordata
Rscript "$SCRIPT_DIR"/summarize_stat_distr.r "$WDIR"/ref_dxy_distr.tab Dxy 25
# Pi - E. cordata
Rscript "$SCRIPT_DIR"/summarize_stat_distr.r "$WDIR"/cordata_pi_distr.tab Pi 25
# Pi - E. globulus MR
Rscript "$SCRIPT_DIR"/summarize_stat_distr.r "$WDIR"/globmr_pi_distr.tab Pi 25
# Pi - E. globulus reference
Rscript "$SCRIPT_DIR"/summarize_stat_distr.r "$WDIR"/globref_pi_distr.tab Pi 25
# Pi - E. globulus ref and E. cordata
Rscript "$SCRIPT_DIR"/summarize_stat_distr.r "$WDIR"/ref_pi_distr.tab Pi 25
# Pi - All
Rscript "$SCRIPT_DIR"/summarize_stat_distr.r "$WDIR"/all_pi_distr.tab Pi 25
# He - E. cordata
Rscript "$SCRIPT_DIR"/summarize_stat_distr.r "$WDIR"/cordata_he_distr.tab He 25
# He - E. globulus MR
Rscript "$SCRIPT_DIR"/summarize_stat_distr.r "$WDIR"/globmr_he_distr.tab He 25
# He - E. globulus ref
Rscript "$SCRIPT_DIR"/summarize_stat_distr.r "$WDIR"/globref_he_distr.tab He 25
# He - E. globulus (all)
Rscript "$SCRIPT_DIR"/summarize_stat_distr.r "$WDIR"/glob_he_distr.tab He 25