#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=hmm_lai
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=30gb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=ancestryhmm_%j.out
#SBATCH --error=ancestryhmm_%j.err

module load ancestryhmm/1.0.2
LIST_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/ancestry_hmm"

# Run Ancestry_HMM
# Arguments:
# -i: input of genotype counts among reference and introgressed samples
# -s: ploidy of each sample, all diploid
# -a: two source populations, 0 (E. globulus) contributed 99% of variation and 1 (E. cordata) contributed 1%
# -p: first ancestry pulse for glob background, num generations set above limit to indicate starting background, 99% of current admixed genomes 
# -p: second ancestry pulse for cordy background, start at 1700 generations (assuming pleistocene admixture and generation times of 10 years) and optimize, 1% of current admixed genomes but optimize estimate
# -g: genotype counts provided rather than read pileups
# -b: do 100 bootstraps of 10,000 SNP blocks
# -ne: effective population size of the admixed population -- I don't know this, so I'm not going to try to provide it.

ancestry_hmm -i all_ahmm_in_aims.tab -s "$LIST_DIR"/sample_ploidy.txt -a 2 0.99 0.01 -p 0 100000 0.99 -p 1 -1700 0.01 -g -b 100 1000
