#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=plot_posts
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=plot_posteriors_%j.out
#SBATCH --error=plot_posteriors_%j.err

module load R/4.2
WDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/ancestry_hmm"
SCRIPT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"

while read NAME
do
    Rscript "$SCRIPT_DIR"/plot_posteriors.r "$WDIR"/02.aims/posteriors/"$NAME".posterior "goldenrod1,green3,deepskyblue4"
done < "$WDIR"/Eglobulus_MR.txt

