#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis
#SBATCH --job-name=fbchr3_3
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=10gb
#SBATCH --time=20-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=freebayes_chr03_3_%j.out
#SBATCH --error=freebayes_chr03_3_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load freebayes/1.3.2

LIST_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/03.freebayes/parallel/Chr03"
REF_FILE="/blue/soltis/kasey.pham/euc_hyb_reseq/refs/Eglobulus_genome_X46/EGLOB-X46.v1.0.fa"
OUTDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/03.freebayes/parallel/Chr03"

# Run FreeBayes on all samples at once against E. globulus reference genome, call sites with a maximum depth of 3000
# Chromosome 3, Section 3: 13109451 bp to 19664175 bp
freebayes -L "$LIST_DIR"/bam_inputs_chr03_03.txt -f "$REF_FILE" -v "$OUTDIR"/chr03_03.vcf -g 3000
