#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis
#SBATCH --job-name=fbchr5_7
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=5gb
#SBATCH --time=10-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=freebayes_chr05_7_%j.out
#SBATCH --error=freebayes_chr05_7_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load freebayes/1.3.2

LIST_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/03.freebayes/parallel/Chr05"
REF_FILE="/blue/soltis/kasey.pham/euc_hyb_reseq/refs/Eglobulus_genome_X46/EGLOB-X46.v1.0.fa"
OUTDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/03.freebayes/parallel/Chr05"

# Run FreeBayes on all samples at once against E. globulus reference genome, call sites with a maximum depth of 3000
# Chromosome 5, Section 7: 37751989-44043986
freebayes -L "$LIST_DIR"/bam_inputs_chr05_07.txt -f "$REF_FILE" -v "$OUTDIR"/chr05_07.vcf -g 3000
