#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=mafft
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=2gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=8
#SBATCH --nodes=1
#SBATCH --output=mafft_%j.out
#SBATCH --error=mafft_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load mafft/7.490

mafft --localpair --maxiterate 1000 --thread 8 cp_assemblies.fsa > cp_assemblies_aligned.fsa

