#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=gavg05g
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=genomewide_r2_avg_%j.out
#SBATCH --error=genomewide_r2_avg_%j.err

module load python/3.8
SCRIPT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts" 

python "$SCRIPT_DIR"/genomewide_r2_avg.py {CHR}_r2_glob05.csv
