#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=fblast
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=9
#SBATCH --nodes=1
#SBATCH --output=fdiffs_blast_%j.out
#SBATCH --error=fdiffs_blast_%j.err

module load ncbi_blast/2.15.0
FDIFFS_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/go_enrich/fdiffs/recip_blast"
REFS_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/refs/AUSX01_v2/annotation"
export BLAST_DB="/blue/soltis/kasey.pham/euc_hyb_reseq/refs/AUSX01_v2/annotation:/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/go_enrich/fdiffs/recip_blast"

blastn -query "$FDIFFS_DIR"/Eglob_all_fdiffs_genes.fas -db Egrandis_297_v2.0.cds.fa -outfmt 6 -evalue 0.01 -num_threads 8 -out Eglob_fdiffs_to_AUSX01_cds_BLAST.tab

blastn -query "$REFS_DIR"/Egrandis_297_v2.0.cds.fa -db Eglob_all_fdiffs_genes.fas -outfmt 6 -evalue 0.01 -num_threads 8 -out AUSX01_cds_to_Eglob_fdiffs_BLAST.tab