#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=formatbeag
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=format_beagle_%j.out
#SBATCH --error=format_beagle_%j.err

module load vcftools/0.1.16
module load bcftools/1.15

INDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/04.filter_snps/maf0.00"
LIST_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq"
NAME="meehan_all_fil_maf0.00_snps"

export MISS=1.0

vcftools --vcf "$INDIR"/"$NAME".vcf --max-missing $MISS --min-alleles 2 --not-chr ChrUn --recode --stdout | bcftools view -S "$LIST_DIR"/sample_ids.txt - | bcftools filter -e 'FORMAT/GT="hap"' -O v - | bcftools sort -O v - > "$NAME"_beagle_formatted.vcf
