#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis
#SBATCH --job-name=fbchr7_6
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=5gb
#SBATCH --time=10-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=freebayes_chr07_6_%j.out
#SBATCH --error=freebayes_chr07_6_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load freebayes/1.3.2

LIST_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/03.freebayes/parallel/Chr07"
REF_FILE="/blue/soltis/kasey.pham/euc_hyb_reseq/refs/Eglobulus_genome_X46/EGLOB-X46.v1.0.fa"
OUTDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/03.freebayes/parallel/Chr07"

# Run FreeBayes on all samples at once against E. globulus reference genome, call sites with a maximum depth of 3000
# Chromosome 7, Section 6: 27126316-32551578
freebayes -L "$LIST_DIR"/bam_inputs_chr07_06.txt -f "$REF_FILE" -v "$OUTDIR"/chr07_06.vcf -g 3000
