#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=fbcontigs
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=5gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=freebayes_contigs_%j.out
#SBATCH --error=freebayes_contigs_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load freebayes/1.3.2

freebayes -L /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/freebayes/bam_inputs.txt -f /blue/soltis/kasey.pham/euc_hyb_reseq/refs/ASM1654582v1/GCF_016545825.1_ASM1654582v1_genomic.fna -t /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/freebayes/ASM1654582_unanchored_contigs.bed  -v /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/freebayes/max_dp_3000/unanchored_contigs.vcf
