#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=cplot
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=5gb
#SBATCH --time=5:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=chr_plot_%j.out
#SBATCH --error=chr_plot_%j.err

module purge
module load R/4.3

# LOCATIONS OF FILES
SCRIPT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"
WDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/genome_scan/chr_plots"
PIXY_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/genome_scan/pixy"
DSUITE_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/genome_scan/dsuite"
LD_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/ld/glob/curve_fit/windows"
RECOMB_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/recomb/glob"
VCFT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/genome_scan/vcftools"
AHMM_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/ancestry_hmm/01.all_vars/maf00/posteriors"
ELAI_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/elai/g4000/maf00/output/avg"

declare -a CHR_LIST=(Chr01 Chr02 Chr03 Chr04 Chr05 Chr06 Chr07 Chr08 Chr09 Chr10 Chr11)
declare -a CHR_SIZE=(42219553 50828380 65547241 38599333 62919971 52140660 54252628 70214608 38300324 38722660 42056460)

# test
# >&2 echo doing Chr01
# Rscript "$SCRIPT_DIR"/plot_chr_wins.r -c Chr01 -s 42219553 -o Eglob -n "$VCFT_DIR"/fixed_diffs_globref_cord.tab -p "$PIXY_DIR"/all_pi.txt -y "$PIXY_DIR"/all_dxy.txt -f "$PIXY_DIR"/all_fst.txt -d "$DSUITE_DIR"/localFstats_40_20.txt -l "$LD_DIR"/glob_all_windows_ld.txt -r "$RECOMB_DIR"/all_fil_biallelic_globMR_all.PREDICT.BSCORRECTED.txt -t "$VCFT_DIR"/globMR_.Tajima.D -a "$WDIR"/ahmm_filelist.txt -e "$ELAI_DIR"/Chr01_avg.ps21.txt -i "$ELAI_DIR"/Chr01_avg.snpinfo.txt -g /blue/soltis/kasey.pham/euc_hyb_reseq/analyses/elai/Eglobulus_MR.fam

# real loop
for i in {0..10}
do
    >&2 echo doing ${CHR_LIST[$i]}
    Rscript "$SCRIPT_DIR"/plot_chr_wins.r -c ${CHR_LIST[$i]} -s ${CHR_SIZE[$i]} -o Eglob -n "$VCFT_DIR"/fixed_diffs_globref_cord.tab -p "$PIXY_DIR"/all_pi.txt -y "$PIXY_DIR"/all_dxy.txt -f "$PIXY_DIR"/all_fst.txt -d "$DSUITE_DIR"/localFstats_40_20.txt -l "$LD_DIR"/glob_all_windows_ld.txt -r "$RECOMB_DIR"/all_fil_biallelic_globMR_all.PREDICT.BSCORRECTED.txt -t "$VCFT_DIR"/globMR_.Tajima.D -a "$WDIR"/ahmm_filelist.txt -e "$ELAI_DIR"/"${CHR_LIST[$i]}"_avg.ps21.txt -i "$ELAI_DIR"/"${CHR_LIST[$i]}"_avg.snpinfo.txt -g "$ELAI_DIR"/../../../../Eglobulus_MR_inds.txt
done
