#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=deta
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=600mb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=deta_windows_%j.out
#SBATCH --error=deta_windows_%j.err

module load conda 

ENV_DIR="/blue/soltis/kasey.pham/conda/envs"
SCRIPT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"
VCF_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/04.filter_snps"
WDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/genome_scan/egglib"
declare -a VCFLIST=(chr01 chr02 chr03 chr04 chr05 chr06 chr07 chr08 chr09 chr10 chr11 chrUn)


conda activate "$ENV_DIR"/euc_hyb_reseq

for NAME in "${VCFLIST[@]}"
do
    python "$SCRIPT_DIR"/stats_windows.py "$VCF_DIR"/"$NAME"_fil.vcf Deta 5000 2500 "$WDIR"/glob_structure.json "$WDIR"/glob_outgroup.json "$WDIR"/chr_list.txt "$NAME"_glob_deta_windows.tab
done
