#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=dsuite
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=dsuite_%j.out
#SBATCH --error=dsuite_%j.err

DSUITE_DIR="/blue/soltis/kasey.pham/bin/Dsuite/Build"
WDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/genome_scan/dsuite"
NAME="meehan_all_fil_maf0.00_snps_biallelic"

"$DSUITE_DIR"/Dsuite Dinvestigate -n "$NAME" "$WDIR"/"$NAME".vcf "$WDIR"/SETS.txt test_trios.txt