#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=dsuite
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=dsuite_%j.out
#SBATCH --error=dsuite_%j.err

module load gcc/9.3.0
module load dsuite/0.4-r49

DSUITE_DIR="/blue/soltis/kasey.pham/bin/Dsuite/Build"
VCF_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/04.filter_snps"
WDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/genome_scan/dsuite"
declare -a VCFLIST=(chr01 chr02 chr03 chr04 chr05 chr06 chr07 chr08 chr09 chr10 chr11 chrUn)

for NAME in "${VCFLIST[@]}"
do
    Dsuite Dinvestigate -n "$NAME" "$VCF_DIR"/"$NAME"_fil.vcf.gz SETS.txt test_trios.txt
done