#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=remout
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=remove_outgr_%j.out
#SBATCH --error=remove_outgr_%j.err

module load vcftools
VCF_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/04.filter_snps/maf0.00"
WDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/genome_scan/pixy"

vcftools --vcf "$VCF_DIR"/meehan_all_fil_maf0.00_snps.vcf --remove-indv SRR10339635 --recode --out "$WDIR"/meehan_all_fil_maf0.00_snps_noout.vcf