#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=summwin
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=600mb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=summarize_windows_%j.out
#SBATCH --error=summarize_windows_%j.err

module load R/4.2

SCRIPT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"
WDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/genome_scan"

# Pi
Rscript "$SCRIPT_DIR"/summarize_stat_distr.r "$WDIR"/glob_pi_windows.tab Pi 25
# Dxy - E. globulus MR to E. globulus ref
Rscript "$SCRIPT_DIR"/summarize_stat_distr.r "$WDIR"/glob_dxy_windows.tab Dxy 25
# Dxy - E. globulus MR to E. cordata
Rscript "$SCRIPT_DIR"/summarize_stat_distr.r "$WDIR"/cord_dxy_windows.tab Dxy 25
# Tajima's D
Rscript "$SCRIPT_DIR"/summarize_stat_distr.r "$WDIR"/glob_deta_windows.tab D 25
# FST
Rscript "$SCRIPT_DIR"/summarize_stat_distr.r "$WDIR"/glob_deta_windows.tab FST 25
