#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=tajd
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=2gb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=tajd_windows_%j.out
#SBATCH --error=tajd_windows_%j.err

module load vcftools/0.1.16

VCF_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/04.filter_snps"
WDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/genome_scan/vcftools"
LIST_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/"

vcftools --gzvcf "$VCF_DIR"/all_fil.vcf.gz --keep "$LIST_DIR"/Ecordata.txt --TajimaD 50000 --out cord
vcftools --gzvcf "$VCF_DIR"/all_fil.vcf.gz --keep "$LIST_DIR"/Eglobulus_MR.txt --TajimaD 50000 --out globMR
vcftools --gzvcf "$VCF_DIR"/all_fil.vcf.gz --keep "$LIST_DIR"/Eglobulus_ref.txt --TajimaD 50000 --out globref
