#!/bin/bash
#SBATCH --job-name=fastqc
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --ntasks=1
#SBATCH --mem=800mb
#SBATCH --time=3-00:00:00
#SBATCH --output=fastqc_%j.out
#SBATCH --error=fastqc_%j.err

pwd; hostname; date

module load fastqc

ls /blue/soltis/kasey.pham/euc_hyb_reseq/reads/trimmed_reads/*.fq | while read NAME; do fastqc -o /blue/soltis/kasey.pham/euc_hyb_reseq/reads/fastqc_trimmed $NAME; done

