#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=iqtree
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=12
#SBATCH --nodes=1
#SBATCH --output=iqtree_%j.out
#SBATCH --error=iqtree_%j.err

module load iq-tree/2.1.3 
WDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/cp_tree"

iqtree -s "$WDIR"/concatenated_cp_aligned.fas -st DNA -B 1000 -m MFP -nt 12 -pre concatenated_cp_aligned 
