#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=swp2
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=500mb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=stairwayplot2_%j.out
#SBATCH --error=stairwayplot2_%j.err

module purge
module load java/1.8.0_31
PROG_DIR="/blue/soltis/kasey.pham/bin/stairway_plot_v2.1.1"

./glob_fold.blueprint.sh 