#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=avg_cvg
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=2gb
#SBATCH --time=2-00:00:00
#SBATCH --cpus-per-task=8
#SBATCH --nodes=1
#SBATCH --output=window_avg_cvg_%j.out
#SBATCH --error=window_avg_cvg_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load python/3.8
SCRIPTDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"
LISTDIR="/blue/soltis/kasey.pham/euc_hyb_reseq"

while read NAME
do 
    python "$SCRIPTDIR"/coverage_window_avgs.py -i "$NAME"_cover.txt -o "$NAME"_cvg_windows.txt -a average_coverage.txt -s 100000 -n "$NAME"
done < "$LISTDIR"/accession_nums.txt

