#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=plot_cvg
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=2gb
#SBATCH --time=2-00:00:00
#SBATCH --cpus-per-task=8
#SBATCH --nodes=1
#SBATCH --output=plot_cvg_%j.out
#SBATCH --error=plot_cvg_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load python/3.8

while read NAME
do 
    python /blue/soltis/kasey.pham/euc_hyb_reseq/scripts/plot_coverage.py "$NAME"_cover.txt "$NAME" average_coverage.txt
done < /blue/soltis/kasey.pham/euc_hyb_reseq/sample_ids.txt

