#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=depth
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu$
#SBATCH --mem=10gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=depth_%j.out
#SBATCH --error=depth_%j.err

module load samtools/1.12

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S320_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4190_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S328_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1119_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S336_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/6015_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S344_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4118_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S352_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4376a_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S321_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/5506_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S329_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/6024_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S337_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4216_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S345_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4220_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S353_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1081_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S322_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1129_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S330_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4223_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S338_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4229_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S346_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1043_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S354_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/6029_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S323_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1130_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S331_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/2899a_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S339_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1116_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S347_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/6012_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S355_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/5502c_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S324_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/cord5_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S332_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4224_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S340_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4110_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S348_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4207_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S356_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/2003_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S325_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4246_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S333_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/2897a_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S341_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1051_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S349_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/5504_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S357_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1059_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S326_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/cord3_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S334_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/5500_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S342_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4505_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S350_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/2025_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S358_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4241_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S327_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1056_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S335_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1128_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S343_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4112_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S351_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4507_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S359_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/5509_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S1_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4190_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S9_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1119_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S17_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/6015_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S25_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4118_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S33_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4376a_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S2_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/5506_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S10_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/6024_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S18_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4216_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S26_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4220_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S34_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1081_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S3_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1129_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S11_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4223_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S19_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4229_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S27_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1043_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S35_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/6029_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S4_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1130_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S12_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/2899a_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S20_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1116_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S28_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/6012_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S36_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/5502c_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S5_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/cord5_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S13_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4224_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S21_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4110_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S29_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4207_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S37_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/2003_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S6_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4246_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S14_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/2897a_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S22_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1051_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S30_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/5504_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S38_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1059_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S7_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/cord3_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S15_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/5500_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S23_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4505_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S31_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/2025_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S39_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4241_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S8_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1056_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S16_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/1128_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S24_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4112_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S32_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/4507_marked.bam

samtools depth -o /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth/S40_cover.txt /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/04.markdup/5509_marked.bam


