#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=index
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=5gb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=8
#SBATCH --nodes=1
#SBATCH --output=index_%j.out
#SBATCH --error=index_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load samtools/1.12

while read NAME
do 
    samtools index -b -@ 7 "$NAME"_marked.bam "$NAME"_marked.bai
done < /blue/soltis/kasey.pham/euc_hyb_reseq/seq_ids.txt
