#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=bowtie
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=6gb
#SBATCH --time=4-00:00:00
#SBATCH --cpus-per-task=16
#SBATCH --nodes=1
#SBATCH --output=map_reads_%j.out
#SBATCH --error=map_reads_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load bowtie2/2.4.2
READS_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/reads/trimmed_reads"
OUTDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/01.map_reads"
LIST_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq"

export BOWTIE2_INDEXES="/blue/soltis/kasey.pham/euc_hyb_reseq/refs/Eglobulus_genome_X46"

while read NAME
do 
    bowtie2 -p 16 -q --end-to-end -x EGLOB-X46.v1 -1 "$READS_DIR"/"$NAME"_R1_paired.fq -2 "$READS_DIR"/"$NAME"_R2_paired.fq -S "$OUTDIR"/"$NAME"_mapped.sam --no-unal
done < "$LIST_DIR"/seq_ids.txt

