#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=markdup
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=2gb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=8
#SBATCH --nodes=1
#SBATCH --output=markdup_%j.out
#SBATCH --error=markdup_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load samtools/1.12

while read NAME
do 
    samtools markdup -d 2500 -@ 7 /blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/process_reads/03.sort/"$NAME"_sorted.bam "$NAME"_marked.bam
done < /blue/soltis/kasey.pham/euc_hyb_reseq/seq_ids.txt
