#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=plt_cvg
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=10gb
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=plot_cvg_%j.out
#SBATCH --error=plot_cvg_%j.err

pwd; hostname; date
echo Working directory is $SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR

module purge
module load R/4.2
SCRIPTDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"
LISTDIR="/blue/soltis/kasey.pham/euc_hyb_reseq"
REFDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/refs/Eglobulus_genome_X46"
INDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/02.process_reads/05.depth"

Rscript "$SCRIPTDIR"/plot_coverage.r -i sample_cov_list.txt -n "$LISTDIR"/accessions_by_pop.tab -o pop_cov.png -m "$REFDIR"/chr_names_list.txt -p "$REFDIR"/X46_chr_size_list.txt -s 100000 -c 100000000