#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=wg_pca
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=1gb
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=wg_pca_outl_check_%j.out
#SBATCH --error=wg_pca_outl_check_%j.err

module load plink/1.90b3.39 

INFILE00="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/04.filter_snps/maf0.00/meehan_all_fil_maf0.00_snps.vcf"
INFILE05="/blue/soltis/kasey.pham/euc_hyb_reseq/call_snps/04.filter_snps/maf0.05/meehan_all_fil_maf0.05_snps.vcf"
BASE_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/wg_pca"

plink --vcf "$INFILE00" --double-id --allow-extra-chr --set-missing-var-ids @:# --extract "$BASE_DIR"/maf0.00/all_maf0.00.prune.in --vcf-half-call m --make-bed --pca --remove to_remove.fam --out all_maf0.00_outl_check
plink --vcf "$INFILE05" --double-id --allow-extra-chr --set-missing-var-ids @:# --extract "$BASE_DIR"/maf0.05/all_maf0.05.prune.in --vcf-half-call m --make-bed --pca --remove to_remove.fam --out all_maf0.05_outl_check
