#!/bin/bash
#SBATCH --account=soltis
#SBATCH --qos=soltis-b
#SBATCH --job-name=procwin
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kasey.pham@ufl.edu
#SBATCH --mem=600mb
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --output=process_windows_%j.out
#SBATCH --error=process_windows_%j.err

module load R/4.2

SCRIPT_DIR="/blue/soltis/kasey.pham/euc_hyb_reseq/scripts"
WDIR="/blue/soltis/kasey.pham/euc_hyb_reseq/analyses/genome_scan"

# Pi
Rscript "$SCRIPT_DIR"/process_stat_windows.r "$WDIR"/glob_pi_windows.tab Pi sd 2 above 25
# Dxy - E. globulus MR to E. globulus ref
Rscript "$SCRIPT_DIR"/process_stat_windows.r "$WDIR"/glob_dxy_windows.tab Dxy sd 2 above 25
# Dxy - E. globulus MR to E. cordata
Rscript "$SCRIPT_DIR"/process_stat_windows.r "$WDIR"/cord_dxy_windows.tab Dxy sd 2 below 25
# Tajima's D
Rscript "$SCRIPT_DIR"/process_stat_windows.r "$WDIR"/glob_deta_windows.tab Deta sd 2 below 25
